services:
  datacatalog-harvester:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: ../devops/.env
    volumes:
      - ..:/workspace
      - m2:/home/vscode/.m2
      - tomcat-webapps:/opt/tomcat/webapps
      - ../devops/setenv.sh:/opt/tomcat/bin/setenv.sh
      - ../devops/authentication:/opt/tomcat/conf/authentication
    hostname: localhost
    ports:
      - "7011:8080"
      - "5006:5005"
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      es_node: opensearch
      gpt_elasticPort: 9200
      gpt_elasticHttps: false
      gpt_base64Iv: not-used-but-exception-if-not-provided
      gpt_base64Key: not-used-but-exception-if-not-provided
      gpt_elasticUser: admin
      gpt_authentication: authentication-simple.xml
    command: ["bash", "-c", "/opt/tomcat/bin/catalina.sh run"]

volumes:
  m2:
  tomcat-webapps:
